### ISSUE TITLE
classify_nodes.py - Attribute Error: 'list' object has no attribute 'read' 

### ISSUE THREAD

**Issue by Bananaboy99** [booz-allen-hamilton/DSB3Tutorial#16]
Hey, 

I got a problem running the clasify_nodes.py script. I get the Error down below and if I try to use the nodules.npy directly, I cannot find it. Where is the nodules.npy file? Why do I get this Error? 
Thx for your help. 

`/usr/lib64/python3.4/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "classify_nodes.py", line 144, in <module>
    getRegionMetricRow(argv[1:])
  File "classify_nodes.py", line 22, in getRegionMetricRow
    seg = np.load(fname)
  File "/usr/lib64/python3.4/site-packages/numpy/lib/npyio.py", line 402, in load
    magic = fid.read(N)
AttributeError: 'list' object has no attribute 'read'
`

**Comment by hassanimam1** [comment]
Hey I get the same error (unfortunately).... I hope it has been solved by now... please if anyone could help...

**Comment by qxyjyj** [comment]
@Bananaboy99   I get the same error. Have you solved it?

**Comment by aszhanghuali** [comment]
I get the same error. Have you solved it?

> 我有同样的错误，我怎么能得到结节。
I get the same error. Have you solved it?

**Comment by aszhanghuali** [comment]
@Bananaboy99 
Hi!
I get the same error. Have you solved it?

**Comment by aszhanghuali** [comment]
@qxyjyj 
Hi!
I get the same error. Have you solved it?Thanks

**Comment by qxyjyj** [comment]
Sorry, I have not solved it. So I abandoned that approach.
On 1/5/2019 19:34，aszhanghuali<notifications@github.com> wrote：

@Bananaboy99
Hi!
I get the same error. Have you solved it?
